"""empty message

Revision ID: 0934bcac11e0
Revises: 79ddc8b3910a
Create Date: 2018-11-07 16:33:54.543147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0934bcac11e0'
down_revision = '79ddc8b3910a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('article_img', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'article_img')
    # ### end Alembic commands ###
