"""empty message

Revision ID: 0a74c960e522
Revises: 0934bcac11e0
Create Date: 2018-11-07 16:55:04.250895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a74c960e522'
down_revision = '0934bcac11e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('head_img', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'head_img')
    # ### end Alembic commands ###
