"""empty message

Revision ID: 0c948aa929c7
Revises: 30e9d3d8fccd
Create Date: 2018-09-29 15:53:32.810463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c948aa929c7'
down_revision = '30e9d3d8fccd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('second_tags', sa.String(length=64), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'second_tags')
    # ### end Alembic commands ###
