"""empty message

Revision ID: 3aeca44841c0
Revises: 7f938fcac4a8
Create Date: 2019-03-08 13:35:09.009118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3aeca44841c0'
down_revision = '7f938fcac4a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('file_uuid', sa.String(length=64), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image', 'file_uuid')
    # ### end Alembic commands ###
