"""empty message

Revision ID: 7afeac227e6e
Revises: 7d4e6e59970e
Create Date: 2018-11-15 15:26:28.072909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7afeac227e6e'
down_revision = '7d4e6e59970e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('article_img_uuid', sa.String(length=64), nullable=True))
    op.create_foreign_key(None, 'article', 'image', ['article_img_uuid'], ['image_uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'article', type_='foreignkey')
    op.drop_column('article', 'article_img_uuid')
    # ### end Alembic commands ###
