"""empty message

Revision ID: 7d4e6e59970e
Revises: c01a5c95b04d
Create Date: 2018-11-14 17:36:46.325730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d4e6e59970e'
down_revision = 'c01a5c95b04d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_image_create_time'), 'image', ['create_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_image_create_time'), table_name='image')
    op.drop_column('image', 'create_time')
    # ### end Alembic commands ###
