"""empty message

Revision ID: c01a5c95b04d
Revises: cf4d7f884a01
Create Date: 2018-11-14 17:21:48.972081

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c01a5c95b04d'
down_revision = 'cf4d7f884a01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('image_uuid', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('group_name', sa.String(length=64), nullable=False),
    sa.Column('remote_file_id', sa.String(length=128), nullable=False),
    sa.Column('storage_ip', sa.String(length=64), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('image_uuid')
    )
    op.drop_table('picture')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('picture',
    sa.Column('picture_uuid', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('group_name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('remote_file_id', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('storage_ip', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('size', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('picture_url', mysql.VARCHAR(length=128), nullable=False),
    sa.PrimaryKeyConstraint('picture_uuid'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('image')
    # ### end Alembic commands ###
