"""empty message

Revision ID: cf4d7f884a01
Revises: 0a74c960e522
Create Date: 2018-11-14 17:03:43.131813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf4d7f884a01'
down_revision = '0a74c960e522'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('picture_uuid', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('group_name', sa.String(length=64), nullable=False),
    sa.Column('remote_file_id', sa.String(length=128), nullable=False),
    sa.Column('storage_ip', sa.String(length=64), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('picture_url', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('picture_uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image')
    # ### end Alembic commands ###
